# Generated by Django 4.2 on 2023-05-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactus_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
